version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    
    ports:
      - 8080:80
    environment:
      - PMA_HOST=switchback.proxy.rlwy.net:29608
      - PMA_PORT=29608
      - PMA_USER=root
      - PMA_PASSWORD=izBfrNFtSsRPLCmsQaHwtKRqhHHPpzbk